/** Contract tests only: mocked model outputs are not live performance evidence. */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {sparseRank,cosine,fuse,runRag,validateGeneration} from '../server/rag.mjs';
const chunks=JSON.parse(fs.readFileSync('data/chunks.json')).chunks;
test('PDF chunks retain page and chapter references',()=>{assert.equal(chunks.length,100);assert.equal(new Set(chunks.map(c=>c.id)).size,100);assert.equal(chunks.find(c=>c.id==='meal-1').page,3);assert.equal(chunks.find(c=>c.id==='taxi-1').page,4);});
test('clause retrieval finds meal evidence and cosine uses normalisation',()=>{assert.equal(sparseRank('What is the overtime meal limit?',chunks)[0].chunk.policy_id,'meal');assert.equal(cosine([1,0],[2,0]),1);assert.equal(cosine([1,0],[0,1]),0);const s=sparseRank('meal',chunks);assert.equal(new Set(fuse(s,s).map(c=>c.id)).size,6);});
test('reject unknown citations, uncited claims and contradictory abstention',()=>{for(const value of [{abstained:false,statements:[{text:'invented',chunk_ids:['not-retrieved']}],missing_information:[]},{abstained:false,statements:[{text:'uncited',chunk_ids:[]}],missing_information:[]},{abstained:true,statements:[{text:'claim',chunk_ids:['meal-1']}],missing_information:[]}])assert.throws(()=>validateGeneration(value,chunks));});
test('generation receives evidence and returns validated citation IDs',async()=>{let generated=false;const fetchFn=async(url,options)=>{const body=JSON.parse(options.body);assert(options.headers.Authorization.startsWith('Bearer '));if(url.endsWith('embeddings'))return Response.json({data:body.input.map((_,index)=>({index,embedding:Array(256).fill(1)}))});generated=true;assert.equal(body.store,false);assert.equal(body.model,'gpt-4o');const context=JSON.parse(body.input);assert(context.evidence.some(c=>c.chunk_id==='meal-1'));return Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({abstained:false,statements:[{text:'The eligible meal limit is SGD 25.',chunk_ids:['meal-1']}],missing_information:[]})}]}]});};const r=await runRag('What overtime allowance is available?',chunks,{key:'test-only',fetchFn});assert(generated);assert(r.llm_called);assert.equal(r.sources[0].id,'meal-1');});
test('missing secret and invalid input do not call a model',async()=>{await assert.rejects(runRag('meal',chunks,{}));await assert.rejects(runRag('',chunks,{key:'test-only'}));});
test('API failure cannot silently become a generated answer',async()=>{await assert.rejects(runRag('meal',chunks,{key:'test-only',fetchFn:async()=>new Response('',{status:429})}));});
test('Worker serves files, blocks missing credentials and origin mismatch',async()=>{const {default:w}=await import('../dist/server/index.js');let r=await w.fetch(new Request('https://example.test/api/status'),{});assert.equal((await r.json()).rag_configured,false);r=await w.fetch(new Request('https://example.test/api/ask',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"question":"meal"}'}),{});assert.equal(r.status,503);r=await w.fetch(new Request('https://example.test/api/ask',{method:'POST',headers:{origin:'https://wrong.test'}}),{});assert.equal(r.status,403);r=await w.fetch(new Request('https://example.test/'),{});assert.equal(r.status,200);assert(r.headers.get('Content-Security-Policy').includes("frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"));assert((await r.text()).includes('Live RAG'));r=await w.fetch(new Request('https://example.test/server/rag.mjs'),{});assert.equal(r.status,404);});
